ENV http_proxy=http://10.229.18.27:8412
ENV https_proxy=http://10.229.18.27:8412

RUN pip install --no-cache-dir \
    mathruler qwen_vl_utils math-verify liger-kernel swanlab

ENV VLLM_USE_V1=1
ENV VLLM_NO_USAGE_STATS=1
ENV VLLM_DO_NOT_TRACK=1
ENV PYTHONUNBUFFERED=1
ENV TOKENIZERS_PARALLELISM=false

ENV http_proxy=
ENV https_proxy=
